### ISSUE TITLE
Exception in log when IJ closing

### ISSUE THREAD

**Issue by ChrisCarini** [ChrisCarini/logshipper-intellij-plugin#1]
```
2020-11-28 21:57:55,914 [ 668850]  ERROR - llij.ide.plugins.PluginManager - Cannot create com.intellij.openapi.application.ApplicationInfo because container is already disposed: Application (containerState=DISPOSE_COMPLETED)  
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.openapi.application.ApplicationInfo because container is already disposed: Application (containerState=DISPOSE_COMPLETED) 
	at com.intellij.serviceContainer.ComponentManagerImpl.throwContainerIsAlreadyDisposed(ComponentManagerImpl.kt:447)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:423)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:395)
	at com.intellij.openapi.application.ApplicationInfo.getInstance(ApplicationInfo.java:17)
	at com.intellij.openapi.application.ex.ApplicationInfoEx.getInstanceEx(ApplicationInfoEx.java:15)
	at com.chriscarini.jetbrains.logshipper.logger.LogstashJSONSocketAppender.append(LogstashJSONSocketAppender.java:36)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.log(Log4jLoggerAdapter.java:581)
	at io.netty.util.internal.logging.LocationAwareSlf4JLogger.log(LocationAwareSlf4JLogger.java:46)
	at io.netty.util.internal.logging.LocationAwareSlf4JLogger.warn(LocationAwareSlf4JLogger.java:209)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1047)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ChrisCarini** [comment]
Should have something for this - just published version `2.2.2` which is waiting for approval right now.
